name: Build and Run Sender Receiver with Integration

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
    - name: Run and collect coverage
      run: |
        coverage run --branch Sender/Sender.test.py
        coverage html
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./htmlcov
        retention-days: 1
        
    - name: install coverage tool
      run: sudo apt-get install -y gcovr

    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o receiver bms-stream-receiver/*.cpp
      
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o receiver-test test/*.cpp bms-stream-receiver/bms-stream-receiver.cpp

    - name: run
      run: ./receiver-test 

    - name: run executable integration 
      run: python Sender/Sender.py | ./receiver 

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html

    - name: create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 1
