name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: sudo apt-get install -y gcovr

    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o receiver bms-stream-receiver/*.cpp
      
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o receiver-test test/*.cpp bms-stream-receiver/bms-stream-receiver.cpp
      
    - name: run
      run: ./sender

    - name: run
      run: ./sender-test 

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html

    - name: create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 1
